spring.application.name=Assingments
# === Database Connection ===
spring.datasource.url=jdbc:mysql://localhost:3306/testdb
spring.datasource.username=root
spring.datasource.password=Rootuser@023

# === Optional Hibernate (JPA) Config ===
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
myapp.greeting=Good Afternoon